"""Add ON DELETE CASCADE to all

Revision ID: 0fa6ef558690
Revises: c6f76843eea2
Create Date: 2025-05-14 01:31:01.583804

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0fa6ef558690'
down_revision: Union[str, None] = 'c6f76843eea2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('admins_id_fkey', 'admins', type_='foreignkey')
    op.create_foreign_key(None, 'admins', 'users', ['id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('buses_admin_id_fkey', 'buses', type_='foreignkey')
    op.create_foreign_key(None, 'buses', 'admins', ['admin_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('events_bus_id_fkey', 'events', type_='foreignkey')
    op.create_foreign_key(None, 'events', 'buses', ['bus_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('notification_recipient_notification_id_fkey', 'notification_recipient', type_='foreignkey')
    op.drop_constraint('notification_recipient_user_id_fkey', 'notification_recipient', type_='foreignkey')
    op.create_foreign_key(None, 'notification_recipient', 'notifications', ['notification_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'notification_recipient', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('parent_notification_preferences_parent_id_fkey', 'parent_notification_preferences', type_='foreignkey')
    op.create_foreign_key(None, 'parent_notification_preferences', 'parents', ['parent_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('parent_student_parent_id_fkey', 'parent_student', type_='foreignkey')
    op.create_foreign_key(None, 'parent_student', 'parents', ['parent_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('parent_student_notifications_parent_id_fkey', 'parent_student_notifications', type_='foreignkey')
    op.create_foreign_key(None, 'parent_student_notifications', 'parents', ['parent_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('parents_id_fkey', 'parents', type_='foreignkey')
    op.create_foreign_key(None, 'parents', 'users', ['id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('students_bus_id_fkey', 'students', type_='foreignkey')
    op.create_foreign_key(None, 'students', 'buses', ['bus_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'students', type_='foreignkey')
    op.create_foreign_key('students_bus_id_fkey', 'students', 'buses', ['bus_id'], ['id'])
    op.drop_constraint(None, 'parents', type_='foreignkey')
    op.create_foreign_key('parents_id_fkey', 'parents', 'users', ['id'], ['id'])
    op.drop_constraint(None, 'parent_student_notifications', type_='foreignkey')
    op.create_foreign_key('parent_student_notifications_parent_id_fkey', 'parent_student_notifications', 'parents', ['parent_id'], ['id'])
    op.drop_constraint(None, 'parent_student', type_='foreignkey')
    op.create_foreign_key('parent_student_parent_id_fkey', 'parent_student', 'parents', ['parent_id'], ['id'])
    op.drop_constraint(None, 'parent_notification_preferences', type_='foreignkey')
    op.create_foreign_key('parent_notification_preferences_parent_id_fkey', 'parent_notification_preferences', 'parents', ['parent_id'], ['id'])
    op.drop_constraint(None, 'notification_recipient', type_='foreignkey')
    op.drop_constraint(None, 'notification_recipient', type_='foreignkey')
    op.create_foreign_key('notification_recipient_user_id_fkey', 'notification_recipient', 'users', ['user_id'], ['id'])
    op.create_foreign_key('notification_recipient_notification_id_fkey', 'notification_recipient', 'notifications', ['notification_id'], ['id'])
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.create_foreign_key('events_bus_id_fkey', 'events', 'buses', ['bus_id'], ['id'])
    op.drop_constraint(None, 'buses', type_='foreignkey')
    op.create_foreign_key('buses_admin_id_fkey', 'buses', 'admins', ['admin_id'], ['id'])
    op.drop_constraint(None, 'admins', type_='foreignkey')
    op.create_foreign_key('admins_id_fkey', 'admins', 'users', ['id'], ['id'])
    # ### end Alembic commands ###
