"""Add ON DELETE CASCADE to notifications.event_id

Revision ID: c6f76843eea2
Revises: 158a135d4f81
Create Date: 2025-05-14 01:28:33.842570

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6f76843eea2'
down_revision: Union[str, None] = '158a135d4f81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('notifications_event_id_fkey', 'notifications', type_='foreignkey')
    op.create_foreign_key(None, 'notifications', 'events', ['event_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.create_foreign_key('notifications_event_id_fkey', 'notifications', 'events', ['event_id'], ['id'])
    # ### end Alembic commands ###
